baseURL = 'http://mealaud.com/'
languageCode = 'en-us'
title = 'mel-land'
theme = 'melguy'

[markup]
  [markup.tableOfContents]
    ordered = true
    startlevel = 2
    endlevel = 2
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
    [[menu.main]]
        identifier = "about-me"
        name = "about me"
        url = "/about-me/"
        weight = 0
    [[menu.main]]
        identifier = "math"
        name = "math"
        url = "/math/"
        weight = 1
    [[menu.main]]
        identifier = "hobbies"
        name = "hobbies"
        url = "/hobbies/"
        weight = 2
    [[menu.main]]
        identifier = "misc"
        name = "misc"
        url = "/misc/"
        weight = 3
    # [[menu.main]]
    #     identifier = "journal"
    #     name = "journal"
    #     url= "/journal/"
    #     weight = 4
    [[menu.main]]
        identifier = "axioms"
        name = "axioms"
        url= "/axioms/"
        weight = 5
